version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      PGTZ: 'Asia/Ho_Chi_Minh'
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${PORT}:5432
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./Docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf
      - ./Docker/data/:/var/lib/postgresql/data
    env_file:
      - .env
